CREATE TABLE IF NOT EXISTS Cart(
  id int AUTO_INCREMENT not NULL,
  product_id int not NULL UNIQUE,
  user_id int not NULL UNIQUE,
  quantity int DEFAULT 1,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`id`),
  FOREIGN KEY(`product_id`) REFERENCES Products(`id`),
  FOREIGN KEY(`user_id`) REFERENCES Users(`id`)
)